---
timestamp: '2025-01-15T21:14:27.222976'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs
        relax-all lp066/mystery__pprob17-err-rate-0-1.yaml
    instance_id: mystery__pprob17-err-rate-0-1
    search_algorithm: dfs
    plan_length: 4
    domain_class: mystery
    instance_name: pprob17-err-rate-0-1
    ground_plan:
    - (feast satisfaction potato yogurt guanabara bosnia)
    - (overcome abrasion satisfaction yogurt mercury saturn)
    - (feast satisfaction yogurt wonderbread guanabara bosnia)
    - (succumb abrasion satisfaction wonderbread mercury saturn)
    lifted_plan:
    -   - feast
        - satisfaction
        - potato
        - ?yogurt
        - ?guanabara
        - ?bosnia
    -   - overcome
        - ?abrasion
        - satisfaction
        - ?yogurt
        - ?mercury
        - ?saturn
    -   - feast
        - satisfaction
        - ?yogurt
        - ?wonderbread
        - guanabara
        - ?bosnia
    -   - succumb
        - ?abrasion
        - satisfaction
        - wonderbread
        - mercury
        - saturn


---
timestamp: '2025-01-15T21:14:27.792250'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 0
    repair: ''


---
timestamp: '2025-01-15T21:22:46.015940'
level: ERROR
issuer: batch_solver
event_type: error
data:
    error_type: MemoryError
    error_message: 'Command ''[''/home/projects/u7899572/conda-envs/main/bin/python3'',
        ''instance_solver.py'', ''dfs'', ''/home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1'',
        ''/home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs relax-all
        lp066/mystery__pprob17-err-rate-0-1.yaml'', ''1000000'', ''mystery__pprob17-err-rate-0-1'',
        ''0.66'', ''unary'']'' died with <Signals.SIGKILL: 9>.'
    stack_trace: "Traceback (most recent call last):\n  File \"batch_solver.py\",\
        \ line 126, in worker\n    result = subprocess.run(cmd, check=True, timeout=params['timeout_seconds'],\n\
        \  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/subprocess.py\"\
        , line 516, in run\n    raise CalledProcessError(retcode, process.args,\n\
        subprocess.CalledProcessError: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',\
        \ 'instance_solver.py', 'dfs', '/home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1',\
        \ '/home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs\
        \ relax-all lp066/mystery__pprob17-err-rate-0-1.yaml', '1000000', 'mystery__pprob17-err-rate-0-1',\
        \ '0.66', 'unary']' died with <Signals.SIGKILL: 9>.\n"
    instance_id: mystery__pprob17-err-rate-0-1
    process_info:
        cmd:
        - /home/projects/u7899572/conda-envs/main/bin/python3
        - instance_solver.py
        - dfs
        - /home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1
        - /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs relax-all
            lp066/mystery__pprob17-err-rate-0-1.yaml
        - '1000000'
        - mystery__pprob17-err-rate-0-1
        - '0.66'
        - unary
        duration: '636.93'
        python_executable: /home/projects/u7899572/conda-envs/main/bin/python3
    stdout: ''
    stderr: ''


