---
timestamp: '2025-01-15T22:21:26.791291'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs
        relax-all lp033/freecell__pprobfreecell-3-4-err-rate-0-5.yaml
    instance_id: freecell__pprobfreecell-3-4-err-rate-0-5
    search_algorithm: dfs
    plan_length: 12
    domain_class: freecell
    instance_name: pprobfreecell-3-4-err-rate-0-5
    ground_plan:
    - (sendtohome-b ha h n1 h0 n0 n1 n2)
    - (sendtohome-b ca c n1 c0 n0 n2 n3)
    - (sendtohome da d2 d n1 d0 n0)
    - (sendtohome sa d3 s n1 s0 n0)
    - (sendtohome h2 s2 h n2 ha n1)
    - (sendtohome-b c2 c n2 ca n1 n3 n4)
    - (sendtohome c3 s3 c n3 c2 n2)
    - (sendtohome d2 h3 d n2 da n1)
    - (sendtohome-b d3 d n3 d2 n2 n4 n5)
    - (sendtohome-b h3 h n3 h2 n2 n5 n6)
    - (sendtohome-b s2 s n2 sa n1 n6 n7)
    - (sendtohome-b s3 s n3 s2 n2 n7 n8)
    lifted_plan:
    -   - sendtohome-b
        - ha
        - h
        - n1
        - ?h0
        - n0
        - n1
        - n2
    -   - sendtohome-b
        - ?ca
        - c
        - n1
        - c0
        - n0
        - ?n2
        - n3
    -   - sendtohome
        - da
        - ?d2
        - d
        - n1
        - d0
        - n0
    -   - sendtohome
        - ?sa
        - d3
        - s
        - n1
        - s0
        - ?n0
    -   - sendtohome
        - h2
        - s2
        - h
        - n2
        - ha
        - n1
    -   - sendtohome-b
        - ?c2
        - c
        - n2
        - ?ca
        - n1
        - n3
        - n4
    -   - sendtohome
        - c3
        - ?s3
        - c
        - n3
        - ?c2
        - ?n2
    -   - sendtohome
        - d2
        - ?h3
        - d
        - ?n2
        - da
        - n1
    -   - sendtohome-b
        - d3
        - ?d
        - ?n3
        - d2
        - n2
        - ?n4
        - n5
    -   - sendtohome-b
        - h3
        - h
        - n3
        - h2
        - n2
        - n5
        - n6
    -   - sendtohome-b
        - s2
        - s
        - n2
        - sa
        - ?n1
        - ?n6
        - ?n7
    -   - sendtohome-b
        - s3
        - s
        - n3
        - ?s2
        - n2
        - n7
        - n8


---
timestamp: '2025-01-15T22:21:27.844570'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 2
    repair: 'sendtohome,(home ?card),effPos,1

        sendtohome-b,(home ?card),effPos,1'


---
timestamp: '2025-01-15T22:27:02.760099'
level: ERROR
issuer: batch_solver
event_type: error
data:
    error_type: MemoryError
    error_message: 'Command ''[''/home/projects/u7899572/conda-envs/main/bin/python3'',
        ''instance_solver.py'', ''dfs'', ''/home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1'',
        ''/home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs relax-all
        lp033/freecell__pprobfreecell-3-4-err-rate-0-5.yaml'', ''1000000'', ''freecell__pprobfreecell-3-4-err-rate-0-5'',
        ''0.33'', ''unary'']'' died with <Signals.SIGKILL: 9>.'
    stack_trace: "Traceback (most recent call last):\n  File \"batch_solver.py\",\
        \ line 126, in worker\n    result = subprocess.run(cmd, check=True, timeout=params['timeout_seconds'],\n\
        \  File \"/home/projects/u7899572/conda-envs/main/lib/python3.8/subprocess.py\"\
        , line 516, in run\n    raise CalledProcessError(retcode, process.args,\n\
        subprocess.CalledProcessError: Command '['/home/projects/u7899572/conda-envs/main/bin/python3',\
        \ 'instance_solver.py', 'dfs', '/home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1',\
        \ '/home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs\
        \ relax-all lp033/freecell__pprobfreecell-3-4-err-rate-0-5.yaml', '1000000',\
        \ 'freecell__pprobfreecell-3-4-err-rate-0-5', '0.33', 'unary']' died with\
        \ <Signals.SIGKILL: 9>.\n"
    instance_id: freecell__pprobfreecell-3-4-err-rate-0-5
    process_info:
        cmd:
        - /home/projects/u7899572/conda-envs/main/bin/python3
        - instance_solver.py
        - dfs
        - /home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1
        - /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs relax-all
            lp033/freecell__pprobfreecell-3-4-err-rate-0-5.yaml
        - '1000000'
        - freecell__pprobfreecell-3-4-err-rate-0-5
        - '0.33'
        - unary
        duration: '654.21'
        python_executable: /home/projects/u7899572/conda-envs/main/bin/python3
    stdout: ''
    stderr: ''


