> Solving the next problem at: 2024-09-27 08:17:15 UTC
> Search algorithm: bfs
> Instance ID=hiking-opt14-strips/pptesting-1-2-3-err-rate-0-5
> Plan length=13
> Domain class: hiking-opt14-strips
> Instance name: pptesting-1-2-3-err-rate-0-5
> Ground plan:
['(put_down girl0 place0 tent0)', '(drive_tent girl0 place0 place1 car0 tent0)', '(drive guy0 place0 place1 car1)', '(drive_tent_passenger girl0 place1 place0 car0 tent0 guy0)', '(drive_tent girl0 place0 place1 car0 tent0)', '(put_up girl0 place1 tent0)', '(drive girl0 place1 place0 car0)', '(walk_together tent0 place1 guy0 place0 girl0 couple0)', '(put_down girl0 place1 tent0)', '(drive_tent girl0 place1 place2 car1 tent0)', '(put_up girl0 place2 tent0)', '(drive girl0 place2 place1 car1)', '(walk_together tent0 place2 guy0 place1 girl0 couple0)']
> Lifted plan:
['put_down', 'drive_tent', 'drive', 'drive_tent_passenger', 'drive_tent', 'put_up', 'drive', 'walk_together', 'put_down', 'drive_tent', 'put_up', 'drive', 'walk_together']
>>>  Vanilla ground repair length:
1

>>>  Vanilla ground repair:
put_down,(next ?x2 ?x2),precPos,-1

An error occurred during A* search: name 'logger' is not defined
Traceback (most recent call last):
  File "/home/nader/projects/lifted-white-plan-domain-repair/instance_solver.py", line 70, in solve_instance
    path, goal_node = searcher.find_path(log_interval=log_interval)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nader/projects/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py", line 49, in find_path
    for neighbor in current_node.get_neighbors():
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nader/projects/lifted-white-plan-domain-repair/search_partial_grounding/node.py", line 167, in get_neighbors
    logger.debug(f'> Current state:\n{self.current_state}')
    ^^^^^^
NameError: name 'logger' is not defined. Did you mean: 'self.logger'?

> Time spent on this problem: 0.0 hours = 0.0 minutes = 0.26 seconds
> Subprocess finished.
