> Solving the next problem at: 2024-09-27 08:34:11 UTC
> Search algorithm: bfs
> Instance ID=mystery/pprob14-err-rate-0-5
> Plan length=11
> Domain class: mystery
> Instance name: pprob14-err-rate-0-5
> Ground plan:
['(feast rest scallop lettuce quebec bavaria)', '(feast rest lettuce pistachio arizona pennsylvania)', '(overcome anxiety-25 rest pistachio vulcan jupiter)', '(overcome prostatitis-23 rest pistachio mars vulcan)', '(feast rest pistachio lettuce alsace arizona)', '(feast rest lettuce scallop alsace arizona)', '(feast rest scallop scallion surrey quebec)', '(feast rest scallion shrimp pennsylvania surrey)', '(feast rest shrimp potato pennsylvania surrey)', '(succumb anxiety-25 rest potato mars vulcan)', '(succumb prostatitis-23 rest potato vulcan jupiter)']
> Lifted plan:
['feast', 'feast', 'overcome', 'overcome', 'feast', 'feast', 'feast', 'feast', 'feast', 'succumb', 'succumb']
>>>  Vanilla ground repair length:
2

>>>  Vanilla ground repair:
overcome,(harmony ?v ?s2),effPos,1
overcome,(fears ?c ?v),effPos,1

An error occurred during A* search: name 'logger' is not defined
Traceback (most recent call last):
  File "/home/nader/projects/lifted-white-plan-domain-repair/instance_solver.py", line 70, in solve_instance
    path, goal_node = searcher.find_path(log_interval=log_interval)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nader/projects/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py", line 49, in find_path
    for neighbor in current_node.get_neighbors():
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nader/projects/lifted-white-plan-domain-repair/search_partial_grounding/node.py", line 167, in get_neighbors
    logger.debug(f'> Current state:\n{self.current_state}')
    ^^^^^^
NameError: name 'logger' is not defined. Did you mean: 'self.logger'?

> Time spent on this problem: 0.0 hours = 0.1 minutes = 7.56 seconds
> Subprocess finished.
