> Solving the next problem at: 2024-09-27 08:29:40 UTC
> Search algorithm: bfs
> Instance ID=mystery/pprob28-err-rate-0-5
> Plan length=9
> Domain class: mystery
> Instance name: pprob28-err-rate-0-5
> Ground plan:
['(feast intoxication wurst lamb goias bosnia)', '(feast intoxication lamb broccoli alsace kentucky)', '(overcome boils intoxication broccoli vulcan earth)', '(feast intoxication broccoli muffin alsace kentucky)', '(overcome anger intoxication muffin neptune vulcan)', '(feast intoxication muffin broccoli bosnia pennsylvania)', '(feast intoxication broccoli lamb oregon alsace)', '(succumb anger intoxication lamb neptune vulcan)', '(succumb boils intoxication lamb vulcan earth)']
> Lifted plan:
['feast', 'feast', 'overcome', 'feast', 'overcome', 'feast', 'feast', 'succumb', 'succumb']
>>>  Vanilla ground repair length:
2

>>>  Vanilla ground repair:
feast,(locale ?v ?l2),precPos,-1
overcome,(orbits ?c ?s1),precPos,-1

An error occurred during A* search: name 'logger' is not defined
Traceback (most recent call last):
  File "/home/nader/projects/lifted-white-plan-domain-repair/instance_solver.py", line 70, in solve_instance
    path, goal_node = searcher.find_path(log_interval=log_interval)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nader/projects/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py", line 49, in find_path
    for neighbor in current_node.get_neighbors():
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nader/projects/lifted-white-plan-domain-repair/search_partial_grounding/node.py", line 167, in get_neighbors
    logger.debug(f'> Current state:\n{self.current_state}')
    ^^^^^^
NameError: name 'logger' is not defined. Did you mean: 'self.logger'?

> Time spent on this problem: 0.0 hours = 0.0 minutes = 0.19 seconds
> Subprocess finished.
