---
timestamp: '2025-01-16T11:35:50.291282'
level: INFO
issuer: instance_solver
event_type: metadata
data:
    log_file: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/astar-unary
        relax-prec lp1/pegsol-08-strips__pp01-err-rate-0-1.yaml
    instance_id: pegsol-08-strips__pp01-err-rate-0-1
    search_algorithm: astar
    plan_length: 7
    domain_class: pegsol-08-strips
    instance_name: pp01-err-rate-0-1
    ground_plan:
    - (jump-new-move pos-3-4 pos-2-4 pos-1-4)
    - (end-move pos-1-4)
    - (jump-new-move pos-1-4 pos-1-3 pos-1-2)
    - (end-move pos-1-2)
    - (jump-new-move pos-1-2 pos-2-2 pos-3-2)
    - (end-move pos-3-2)
    - (jump-new-move pos-3-1 pos-3-2 pos-3-3)
    lifted_plan:
    -   - jump-new-move
        - ?pos-3-4
        - ?pos-2-4
        - ?pos-1-4
    -   - end-move
        - ?pos-1-4
    -   - jump-new-move
        - ?pos-1-4
        - ?pos-1-3
        - ?pos-1-2
    -   - end-move
        - ?pos-1-2
    -   - jump-new-move
        - ?pos-1-2
        - ?pos-2-2
        - ?pos-3-2
    -   - end-move
        - ?pos-3-2
    -   - jump-new-move
        - ?pos-3-1
        - ?pos-3-2
        - ?pos-3-3


---
timestamp: '2025-01-16T11:35:50.943719'
level: INFO
issuer: instance_solver
event_type: ground_repair
data:
    repair_length: 1
    repair: jump-new-move,(in-line ?over ?to ?from),precPos,-1


---
timestamp: '2025-01-16T11:35:53.582019'
level: ERROR
issuer: instance_solver
event_type: error
data: "An error occurred during A* search: 'Node' object has no attribute 'neighbours'.\
    \ Stack trace: Traceback (most recent call last):\n  File \"instance_solver.py\"\
    , line 104, in solve_instance\n    searcher.find_path(logger=logger, log_interval=log_interval)\n\
    \  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py\"\
    , line 95, in find_path\n    self.log_iteration_info(logger, iteration, open_list,\
    \ current_node, final=True, is_goal=False)\n  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/search_algorithms.py\"\
    , line 37, in log_iteration_info\n    \"current_node\": current_node.to_dict(include_state=False)\n\
    \  File \"/home/remote/u7899572/lifted-white-plan-domain-repair/search_partial_grounding/node.py\"\
    , line 234, in to_dict\n    \"num_neighbours\": len(self.neighbours),\nAttributeError:\
    \ 'Node' object has no attribute 'neighbours'\n"


---
timestamp: '2025-01-16T11:35:53.741492'
level: INFO
issuer: instance_solver
event_type: timer_seconds
data: '113.13'


---
timestamp: '2025-01-16T11:37:31.409017'
level: INFO
issuer: batch_solver
event_type: general
data: 'Subprocess finished successfully. Duration: 251.99 seconds'


